version: "2.2"

services:
    scraper:
        build:
            context: ./docker
        shm_size: '2gb'
        container_name: <GLOBAL_PREFIX>scraper
        volumes:
            - data:/home/<USER>/data

volumes:
    data:
        name: <GLOBAL_PREFIX>data
        driver_opts:
            type: none
            device: <CURDIR>/vol/data
            o: bind
